
server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: security-component
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  #to limit file size in uploads

springdoc:
  default-produces-media-type: application/json

app:
  security:
    jwt:
      secret-key: V2o4Qk5vWmR0czA5cGdWYkQ5SmRjZVpCSU1iYzhWZ2V5Y0x4cE9Yeg==
      expiration: 3600
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
