
server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: security-component
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  #to limit file size in uploads

springdoc:
  default-produces-media-type: application/json

